<?php
/**
 * CravenDunnill_TileSamples extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category   CravenDunnill
 * @package    CravenDunnill_TileSamples
 * @copyright  Copyright (c) 2025 CravenDunnill
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \CravenDunnill\TileSamples\Block\TileSample $block */
?>
<?php if ($block->isTileSampleAvailable()): ?>
    <div class="tile-sample-button-container">
        <?php if (!$block->isSampleInCart()): ?>
            <form data-role="tile-sample-form" action="<?= $block->escapeUrl($block->getAddToCartUrl()) ?>" method="post">
                <?= $block->getBlockHtml('formkey') ?>
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr(__('Free Cut Sample')) ?>"
                        class="action primary tile-sample-button">
                    <span><?= $block->escapeHtml(__('Free Cut Sample')) ?></span>
                </button>
            </form>
        <?php else: ?>
            <button type="button"
                    disabled="disabled"
                    class="action primary tile-sample-button tile-sample-button-disabled">
                <span><?= $block->escapeHtml(__('Free Cut Sample Already In Cart')) ?></span>
            </button>
        <?php endif; ?>
    </div>
<?php endif; ?>